include: package:flutter_lints/flutter.yaml

analyzer:
  enable-experiment:
    - non-nullable
  strong-mode:
     implicit-casts: false
  errors:
    missing_required_param: error
    prefer_const_declarations: warning
    prefer_const_constructors: warning
    import_of_legacy_library_into_null_safe: ignore
    
linter:
  rules:
    omit_local_variable_types: false
    missing_required_param: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    public_member_api_docs: true
    use_key_in_widget_constructors: true
    prefer_int_literals: true
    lines_longer_than_80_chars: false
    prefer_relative_imports: true
    always_use_package_imports: false
    import_of_legacy_library_into_null_safe: false
    avoid_print: true
    